language: cpp


addons:
  apt:
    sources: 
      - ubuntu-toolchain-r-test
    packages:
      #- g++-4.9
      #- g++-5
      - g++-6
      
matrix:
  include:
    - os: linux
      sudo: false
      env: GCC_VER="6"
      compiler: gcc
  
script: 
  - cmake . 
  - cmake --build . -- -j2
  - ctest

notifications:
  email:
    recipients:
      - arnaud.courbiere@gmail.com
    on_success: always
    on_failure: always
